server:
  port: 9098

spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
    username: "OAUTH2"
    password: 14292
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate

